export enum RoleName {
    ADMIN_CREATE_PIPELINE = 'ROLE_ADMIN_CREATE_PIPELINE',
    ADMIN_VIEW_PIPELINE = 'ROLE_ADMIN_VIEW_PIPELINE',
    ADMIN_STORE_PIPELINE = 'ROLE_ADMIN_STORE_PIPELINE',
    ADMIN_UPDATE_PIPELINE = 'ROLE_ADMIN_UPDATE_PIPELINE',
    ADMIN_DELETE_PIPELINE = 'ROLE_ADMIN_DELETE_PIPELINE',

    ADMIN_VIEW_STAGE = 'ROLE_ADMIN_VIEW_STAGE',

    ADMIN_CREATE_USER = 'ROLE_ADMIN_CREATE_USER',
    ADMIN_VIEW_USER = 'ROLE_ADMIN_VIEW_USER',
    ADMIN_STORE_USER = 'ROLE_ADMIN_STORE_USER',
    ADMIN_UPDATE_USER = 'ROLE_ADMIN_UPDATE_USER',
    ADMIN_DELETE_USER = 'ROLE_ADMIN_DELETE_USER',
}