version: "3"
services:
  vue:
    image: spring-boot-crm-fe/vue
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    working_dir: /usr/src/app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
